### ISSUE TITLE
Unable to access outputs of other templates

### ISSUE THREAD

**Issue by VarunkumarManohar** [GoogleCloudPlatform/deploymentmanager-samples#103]
I have a deployment manager script as follows:
cluster.py creates a kubernetes cluster and when the script was run only for the k8 cluster creation, it was successful -- so it means the cluster.py had no issues in creation of a k8 cluster

cluster.py also exposes ouputs:
A small snippet of the cluster.py is as follows:
```
outputs.append({
        	'name': 'v1endpoint' ,
        	'value': type_name + type_suffix })
    
return {'resources': resources, 'outputs': outputs}
```
    
If I try to access the exposed output inside dmnginxservice resource below as $(ref.dmcluster.v1endpoint) I get an error as resource not found
```
imports:
- path: cluster.py 
- path: nodeport.py

resources:
- name: dmcluster
  type: cluster.py
  properties:
   zone: us-central1-a
      
- name: dmnginxservice
  type: nodeport.py
  properties:
   cluster: $(ref.dmcluster.v1endpoint)
   image: gcr.io/pr1/nginx:latest
   port: 342
   nodeport: 32123
    
```

```
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1519960432614-566655da89a70-a2f917ad-69eab05a]: errors:
- code: CONDITION_NOT_MET
  message: Referenced resource yaml%dmcluster could not be found. At resource
    gke-cluster-dmnginxservice.

```
