### ISSUE TITLE
Cannot create runtime config variables

### ISSUE THREAD

**Issue by VarunkumarManohar** [GoogleCloudPlatform/deploymentmanager-samples#141]
Cannot create a google deployment manager runtime config variable

```
resources:
- name: star-config
  type: runtimeconfig.v1beta1.config
  properties:
    name: star-config

- name: igurl_variable
  type: runtimeconfig.v1beta1.variable
  properties:
   name: igurl_variable
   value: 'trek'
   parent: $(ref.star-config.name)
```
I checked the logs and I see that the status is set to bad_request when I create the above deployment.

Audit log
status: {
   message:  "BAD_REQUEST"

  }
What could be the reason for the error ? Just does not seem obvious.

I also see that when I try to invoke the config create and variable create apis from the Google explorer I see 400 errors..
