### ISSUE TITLE
ResourceError Code 400 when updating GKE addOnsConfig

### ISSUE THREAD

**Issue by jiang-wei** [GoogleCloudPlatform/deploymentmanager-samples#147]
When updading a GKE cluster previously created with DM, get the error.

I've enabled the k8s dashboard manually in the GKE web console, and I'd like to update the DM configuration and I ran the updating command.

Here's the error message:

```json
{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"addons_config must specify values for http_load_balancing and/or horizontal_pod_autoscaling.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/............./clusters/gke-cluster/addons", "httpMethod":"POST"}}
```

the expanded config looks like:
```
resources:
- name: gke-cluster
  properties:
    cluster:
      addonsConfig:
        horizontalPodAutoscaling:
          disabled: false
        httpLoadBalancing:
          disabled: false
        kubernetesDashboard:
          disabled: false                  # used to be true when I previously created the gke cluster
      initialClusterVersion: 1.8.9-gke.1
      legacyAbac:
        enabled: true
      name: gke-cluster
      nodePools:
      - autoscaling:
          enabled: true
          maxNodeCount: 15
          minNodeCount: 1
        config:
          diskSizeGb: 100
          imageType: cos
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring
        initialNodeCount: 2
        management:
          autoRepair: false
          autoUpgrade: false
        name: default-pool
    zone: us-central1-c
  type: container.v1.cluster
```

The addonsConfig is there.
