### ISSUE TITLE
GKE with SharedVPC

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#180]
Hi,
I've a problem creating GKE cluster with SharedVPC using DeploymentManager. If I'll do manually all works great. All the permissions are setup as specified in the documentation

This is my config:
```
resources:
- name: gke-tokyo-1
  type: container.v1.cluster
  properties:
    zone: asia-northeast1-a
    cluster:
      name: gke-tokyo-1
      initialClusterVersion: 1.10.4-gke.2
      locations:
      - asia-northeast1-a
      - asia-northeast1-b
      # I've tried with and without 'https://www.googleapis.com/compute/v1/'
      network: https://www.googleapis.com/compute/v1/projects/my-sharedvpc-project/global/networks/net-l2l
      subnetwork: https://www.googleapis.com/compute/v1/projects/my-sharedvpc-project/regions/asia-northeast1/subnetworks/net-l2l-asia-northeast1-10-222-4-0-22
      ipAllocationPolicy:
        clusterSecondaryRangeName: asia-northeast1-gke-pods-1
        servicesSecondaryRangeName: asia-northeast1-gke-services-1
        useIpAliases: true
      addonsConfig:
        horizontalPodAutoscaling:
          disabled: false
        httpLoadBalancing:
          disabled: false
        kubernetesDashboard:
          disabled: true
      enableKubernetesAlpha: false
      legacyAbac:
        enabled: false
      masterAuth:
        clientCertificateConfig:
          issueClientCertificate: false
        username: ''
      masterAuthorizedNetworksConfig:
        enabled: false
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      networkPolicy:
        enabled: true
        provider: CALICO
      nodePools:
      - autoscaling:
          enabled: true
          maxNodeCount: 3
          minNodeCount: 1
        config:
          diskSizeGb: 20
          imageType: COS
          localSsdCount: 0
          machineType: n1-standard-1
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring
          - https://www.googleapis.com/auth/cloud_debugger
          preemptible: false
        initialNodeCount: 1
        management:
          autoRepair: true
          autoUpgrade: true
        name: test
```

And this is the error:
```
The fingerprint of the deployment is 7nAEPkF6aMcxaRGKoA7iSA==
Waiting for update [operation-1529481788647-56f0e3ab3e658-00186eb8-5b7b877a]...failed.                                                                                                                                                                                                                                       
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1529481788647-56f0e3ab3e658-00186eb8-5b7b877a]: errors:
- code: RESOURCE_ERROR
  location: /deployments/resources/resources/gke-tokyo-1
  message: '{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"must
    use a network belonging to project \"my-service-project\".","status":"INVALID_ARGUMENT","statusMessage":"Bad
    Request","requestPath":"https://container.googleapis.com/v1/projects/my-service-project/zones/asia-northeast1-a/clusters","httpMethod":"POST"}}'
```

Is not supported this setup in DM?
I've seen that someone with Terraform has had a similar problem (https://github.com/terraform-providers/terraform-provider-google/issues/1532) and was resolved with selfLink.
I underline that I've the same IAM setup as https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_container_cluster_test.go#L2129

Thanks
