### ISSUE TITLE
Folder acquire

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#226]
Hi,
I've an organization with two "x" folders under two different folders ("a" and "b"). So
```
Org
|
|- a
|  L x
|
|- b
   L x
```

I've written the following deployment to acquire these resources:
```
- name: x-a-folder
  type: gcp-types/cloudresourcemanager-v2:folders
  properties:
    parent: folders/123456789012 # (a)
    displayName: x
- name: x-b-folder
  type: gcp-types/cloudresourcemanager-v2:folders
  properties:
    parent: folders/123456789013 # (b)
    displayName: x
```

And I have the error:
```
$ gcloud deployment-manager deployments update resources --config resources.yaml --create-policy=acquire
....
- code: RESOURCE_ERROR
  location: /deployments/resources/resources/x-a-folder
  message: '{"ResourceType":"gcp-types/cloudresourcemanager-v2:folders","ResourceErrorCode":"404","ResourceErrorMessage":{"statusMessage":"Not
    Found","requestPath":"https://cloudresourcemanager.googleapis.com/v2/x-a-folder","httpMethod":"GET"}}'
```

In this case how can I say that I want to acquire two resources with name x but that in deployment must have a different name? An optional ```name``` field is not considered by DM

Thanks

**Comment by fawix** [comment]
the construction of the input YAML is incorrect. You should use `folderId` to indicate folders under a parent folder and `orgId` to indicate folders directly under the org. 

So the YAML should look like the following:

```yaml
  properties:
    folders:
      - name: x-a-folder
        folderId: folders/123456789098 # ID of folder a
        displayName: x
      - name: x-b-folder
        folderId: folders/098765432123 # ID of folder b
        displayName: x
```

be sure to checkout the example for the full file.
