### ISSUE TITLE
Missing non mandatory parameter makes deployment fail - project factory

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/deploymentmanager-samples#242]
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/project/project.py.schema
If sharedVPCSubnets is not specified, it is None and not an empty list.

` for i, subnet in enumerate(context.properties.get('sharedVPCSubnets'), 1):`
Enumerate fails because of Null value. It works with empty list. The problem is that sharedVPCSubnets is not flagged as required.

**Comment by bohdanyurov-gl** [comment]
Strange, there shouldn't be any problems, as we have a check in the code:
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/project/project.py#L169
````python
if (
            context.properties.get('sharedVPCSubnets') and
            context.properties.get('sharedVPC')
    ):
````

I've also tried applying this template, it works:
````yaml
imports:
  - path: templates/project/project.py
    name: project.py

resources:
  - name: <FOO>
    type: project.py
    properties:
      parent:
        type: folder
        id: <FOO2>
      billingAccountId: <FOO3>
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
        - pubsub.googleapis.com
      serviceAccounts:
        - accountId: test-sa-1
          displayName: test service account 1
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: true
#      sharedVPC: test-vpc-host-project
#      sharedVPCSubnets:
#        - subnetId: subnet-1
#          region: us-east1
````

Could you please give config example that you've used?
