### ISSUE TITLE
cloudsql - postgres

### ISSUE THREAD

**Issue by jonbcampos** [GoogleCloudPlatform/deploymentmanager-samples#286]
I've been trying to extend the cloudsql mysql example to include POSTGRES options. So what is the deal? For me what fails is the failover section of code. I've tried (as you can see) to set the `locationPreference` because I read that needs to be different from the original. I've also set the `availabilityType: REGIONAL` for the master.

```
{% if properties['failover']['enabled'] %}
- name: {{ ID }}-failover
  type: sqladmin.v1beta4.instance
  properties:
    backendType: SECOND_GEN
    instanceType: READ_REPLICA_INSTANCE
    databaseVersion: {{ properties['cloudsql']['databaseVersion'] }}
    region: {{ properties['cloudsql']['region'] }}
    masterInstanceName: $(ref.{{ ID }}-master.name)
    replicaConfiguration:
      failoverTarget: true
    settings:
      tier: {{ properties['cloudsql']['tier'] }}
      locationPreference:
        zone: {{ properties['failover']['zone'] }}
{% endif %}
```

Any idea what might be the problem? the error isn't very descriptive.

```
{"ResourceType":"sqladmin.v1beta4.instance","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"Invalid instance property.","reason":"invalidInstanceProperty"}],"message":"Invalid instance property.","statusMessage":"Bad Request","requestPath":"https://www.googleapis.com/sql/v1beta4/projects/wrkerz-test-3/instances","httpMethod":"POST"}}
```

<img width="1194" alt="screen shot 2018-10-10 at 9 43 41 pm" src="https://user-images.githubusercontent.com/139469/46777604-a7cb0280-ccd5-11e8-9aaa-c6af929e63b8.png">

**Comment by MrAlias** [comment]
@jonbcampos I just (frustratingly) ran into this same error, but think I found a solution.

From looking at the project audit logs I was trying to deploy to it looked like this was a `500` response from Google rather than what the error leads you to believe would be a `400`.  This led me to manually enable `High availability` directly on the master in the console.  

Unlike what I have seen with MySQL CloudSQL failover replicas, the failover was reported in the console as `Enabled` rather than a separate instance listing.  I was able to describe the master and notice that it was described with the following attributes:

```
failoverReplica:
  available: true
```

Upon removing the failover instance from the template and adding the above properties the deployment worked.  E.g.

```
resources:
- name: {{ ID }}-master
  type: sqladmin.v1beta4.instance
  properties:
    backendType: SECOND_GEN
    instanceType: CLOUD_SQL_INSTANCE
    databaseVersion: {{ properties['cloudsql']['databaseVersion'] }}
    region: {{ properties['cloudsql']['region'] }}
    settings:
      tier: {{ properties['cloudsql']['tier'] }}
      dataDiskSizeGb: {{ properties['cloudsql']['dataDiskSizeGb'] }}
      dataDiskType: {{ properties['cloudsql']['dataDiskType'] }}
      storageAutoResize: true
      replicationType: SYNCHRONOUS
      {% if properties['failover'] %}
      failoverReplica:
        available: true
      {% endif %}
      locationPreference:
        zone: {{ properties['cloudsql']['zone'] }}
      {% if properties['databaseFlags'] %}
      databaseFlags: {{ properties['databaseFlags'] }}
      {% endif %}
      activationPolicy: ALWAYS
      backupConfiguration:
        enabled: true
        binaryLogEnabled: true
        startTime: {{ properties['cloudsql']['backupStartTime'] }}
      ipConfiguration:
        authorizedNetworks: {{ properties['cloudsql']['authorizedNetworks'] }}

{% for i in range(properties['readReplicas']) %}
- name: {{ ID }}-rr-{{ i }}
  type: sqladmin.v1beta4.instance
  properties:
...
```

Ideally the example could be updated to work, but until then hopefully this helps.
