### ISSUE TITLE
declaring empty role bindings for a storage bucket

### ISSUE THREAD

**Issue by rllin-fathom** [GoogleCloudPlatform/deploymentmanager-samples#297]
The below is part of my expanded config pertaining to a bucket.  I have a role binding declared for the bucket.
```
- accessControl:
    gcpIamPolicy:
      bindings:
      - members:
        - serviceAccount:ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com
        role: roles/storage.objectViewer
  metadata:
    dependsOn:
    - PROJECT_ID
    - PROJECT_ID-storage-component.googleapis.com
  name: BUCKET_NAME
  properties:
    location: us
    name: BUCKET_NAME
    project: PROJECT_ID
    storageClass: MULTI_REGIONAL
    versioning:
      enabled: true
  type: gcp-types/storage-v1:buckets
```

What is the correct way to redeclare the bucket without role bindings?

Here is what I have tried:

empty `accessControl`
```
- accessControl: {}
  metadata:
    dependsOn:
    - PROJECT_ID
    - PROJECT_ID-storage-component.googleapis.com
  name: BUCKET_NAME
  properties:
    location: us
    name: BUCKET_NAME
    project: PROJECT_ID
    storageClass: MULTI_REGIONAL
    versioning:
      enabled: true
  type: gcp-types/storage-v1:buckets
```
then I get the following error message when deploying
```
BUCKET_NAME: {"ResourceType":"gcp-types/storage-v1:buckets","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"A policy to update must be provided.","reason":"required"}],"message":"A policy to update must be provided.","statusMessage":"Bad Request","requestPath":"https://www.googleapis.com/storage/v1/b/BUCKET_NAME/iam","httpMethod":"PUT"}}
```
no `accessControl`
```
- metadata:
    dependsOn:
    - PROJECT_ID
    - PROJECT_ID-storage-component.googleapis.com
  name: BUCKET_NAME
  properties:
    location: us
    name: BUCKET_NAME
    project: PROJECT_ID
    storageClass: MULTI_REGIONAL
    versioning:
      enabled: true
  type: gcp-types/storage-v1:buckets
```
I also get the same error message.

I've also tried
```
- accessControl:
    gcpIamPolicy: {}
```
and
```
- accessControl:
    gcpIamPolicy:
      bindings: []
```

Any help would be appreciated!  right now we have to always leave a role binding on every bucket :(
