### ISSUE TITLE
ref to properties of a resource created by a user-defined type provider does not work

### ISSUE THREAD

**Issue by zwcn** [GoogleCloudPlatform/deploymentmanager-samples#306]
Hi,

I'm using deployment manager to create a k8s cluster, a namespace called `abc`, and a configmap. The code is the following:

`cm.yaml`:
```
imports:
  - path: cm.jinja

resources:
  - name: cm
    type: cm.jinja
```

`cm.jinja`:

```
resources:
- name: mycluster
  type: container.v1.cluster
  properties:
    zone: us-east1-b
    cluster:
      name: mycluster
      description: "a k8s cluster"
      initialClusterVersion: 1.9.7-gke.6
      monitoringService: none
      loggingService: none
      nodePools:
      - name: default-pool
        initialNodeCount: 1
        config:
          machineType: n1-standard-1
          preemptible: true
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
        management:
          autoUpgrade: false
          autoRepair: true
        autoscaling:
          enabled: true
          minNodeCount: 1
          maxNodeCount: 2

- name: k8s-type
  type: deploymentmanager.v2beta.typeProvider
  properties:
    options:
      validationOptions:
        schemaValidation: IGNORE_WITH_WARNINGS
      inputMappings:
      - fieldName: name
        location: PATH
        methodMatch: ^(GET|DELETE|PUT)$
        value: $.ifNull($.resource.properties.metadata.name, $.resource.name)
      - fieldName: metadata.name
        location: BODY
        methodMatch: ^(PUT|POST)$
        value: $.ifNull($.resource.properties.metadata.name, $.resource.name)
      - fieldName: Authorization
        location: HEADER
        value: >
          $.concat("Bearer ", $.googleOauth2AccessToken())
    descriptorUrl: https://$(ref.mycluster.endpoint)/swaggerapi/api/v1
- name: k8s-namespace
  type: {{env['project']}}/k8s-type:/api/v1/namespaces
  properties:
    apiVersion: v1
    kind: Namespace
    metadata:
      name: abc
  metadata:
    dependsOn:
    - k8s-type

- name: configmap
  type: {{ env['project'] }}/k8s-type:/api/v1/namespaces/{namespace}/configmaps
  properties:
    apiVersion: v1
    kind: ConfigMap
    namespace: $(ref.k8s-namespace.metedata.name) {# <--- This ref does not work #}
    metadata:
      name: cm
    data:
      foo: bar
  metadata:
    dependsOn:
    - k8s-type
```

When i ran `gcloud deployment-manager deployments create --config=cm.yaml test`, i got the following error:

```bash
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1540493039840-57911fc6b2b01-9997d049-b4888626]: errors:
- code: REFERENCE_VALUE_NOT_FOUND
  location: /deployments/test/resources/k8s-namespace->$.properties
  message: |-
    The reference 'metedata.name' is not found, reason:
    The resource 'k8s-namespace' exists, but the reference value does not, details: Missing property in path $['ref']['k8s-namespace']['metedata']
```

I'm not sure how to reference the namespace name when the configmap is created. Using the same syntax for referencing properties of [Supported GCP Type Providers](https://cloud.google.com/deployment-manager/docs/configuration/supported-gcp-types) worked. What is the recommended approach to get the reference of the namespace name in this scenario?
