### ISSUE TITLE
Cross project resource creation support

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/deploymentmanager-samples#337]
Cloud Foundation Toolkit templates should support creating resources in an other project. This requires the use of type providers. It is a large change, involves extensive testing.

**Comment by AniX** [comment]
Does Deployment Manager support cross project resource creation at all? I can create folders and projects in a single deployment, but for creating resources in projects, I need to create one separate deployment per project.

**Comment by ocsig** [comment]
The fairly newly introduced [ 'gcp-types' ](https://cloud.google.com/deployment-manager/docs/configuration/supported-gcp-types) support project as property because they are directly using the underlying GCP APIs.

However it is debatable how much cross project deployment do you wish to do.
Using the Project Factory to automate project creation and common base setup ( like removing default network, setting up a logging bucket, attachment of shared VPC) can fit well into a deployment which is living in a central project. However I personally prefer to put all resources possible to a deployment living in a project where the actual resource lives. It makes the deployments much easier to review and validate and significantly decrease the chance to accidentally deploy resources to a different project.

Further more the main purpose of using multiple project is the proper separation of resource management. This concept is completely opposite to manage resources mostly from a centralized project.

The price, as you pointed out, is to have many deployments. Which is in my view acceptable. I'm not thinking about deployments, but deployment pipelines. ( See Cloud Foundation pipeline tool currently waiting to be merged to master branch.)

I'm happy to hear your use-case in detail and I'm not against cross project resources if the requirements make it necessary.

**Comment by AniX** [comment]
Do you mean something like the following example would be possible with gcp-types? I didn't understand what is actually different with the new gcp-types in contrast to the old resource types.

```yaml
imports:
- path: setup-projects.py
resources:
# create a few projects (script is based on the deploymentmanager-samples in this repository)
- name: projects
  type: setup-projects.py
  properties:
    foo: bar
# create dataset in the first of the projects that are created earlier:
- name: resources-of-project-a
  type: gcp-types/bigquery-v2:datasets
  properties:
    project: $(ref.projects[0].projectId)
    datasetReference:
      datasetId: my_dataset
    location: US
    friendlyName: My Dataset
    description: This dataset is deployed together with its new parent project
```

I'm going to look into the PR for the pipeline tool you mentioned as I agree with the advantages you have mentioned for multiple deployments. Maybe it would address the concerns I have regarding sub-dividing resource creation into multiple deployments. For one, I don#t always have a 1-to-1 map from repositories to GCP projects. Yet I want to reduce the access devs can have to the actual deployment configurations as I believe that the elevated permissions of the DM service accounts could be abused through this route. And I believe that a single deployment is easier to setup, at least it should be.
