### ISSUE TITLE
$(out) can not access parameters of the output that is a dictionary.

### ISSUE THREAD

**Issue by marko7460** [GoogleCloudPlatform/deploymentmanager-samples#353]
At the moment `$(out)` doesn't support extracting parameter from the output that returns dictionary.

For example take this manifest:
```yaml
outputs:
- finalValue: folders/1111111111111
  name: CORE
  value: $(ref.sato-folders.folders.CORE.name)
resources:
- name: sato-folders
  outputs:
  - finalValue:
      CORE:
        createTime: '2018-11-27T21:58:36.807Z'
        displayName: CORE
        lifecycleState: ACTIVE
        name: folders/111111111
        parent: organizations/1234567890
      EU:
        createTime: '2018-11-27T22:13:47.794Z'
        displayName: EU
        lifecycleState: ACTIVE
        name: folders/22222222222
        parent: organizations/1234567890
      NA:
        createTime: '2018-11-27T21:58:37.313Z'
        displayName: NA
        lifecycleState: ACTIVE
        name: folders/3333333333
        parent: organizations/1234567890
    name: folders
    value:
      CORE:
        createTime: $(ref.CORE.createTime)
        displayName: $(ref.CORE.displayName)
        lifecycleState: $(ref.CORE.lifecycleState)
        name: $(ref.CORE.name)
        parent: $(ref.CORE.parent)
      EU:
        createTime: $(ref.EU.createTime)
        displayName: $(ref.EU.displayName)
        lifecycleState: $(ref.EU.lifecycleState)
        name: $(ref.EU.name)
        parent: $(ref.EU.parent)
      NA:
        createTime: $(ref.NA.createTime)
        displayName: $(ref.NA.displayName)
        lifecycleState: $(ref.NA.lifecycleState)
        name: $(ref.NA.name)
        parent: $(ref.NA.parent)
  properties:
    folders:
    - displayName: NA
      name: NA
      orgId: organizations/1234567890
    - displayName: EU
      name: EU
      orgId: organizations/1234567890
    - displayName: CORE
      name: CORE
      orgId: organizations/1234567890
  resources:
  - name: NA
    type: gcp-types/cloudresourcemanager-v2:folders
  - name: EU
    type: gcp-types/cloudresourcemanager-v2:folders
  - name: CORE
    type: gcp-types/cloudresourcemanager-v2:folders
  type: folder.py
```
If i want to create a project under CORE i would have to do something like this
```yaml
name: host-project
imports:
  - path: ../../../deploymentmanager-samples/community/cloud-foundation/templates/project/project.py
    name: project.py
project: {{env.CFT_BOOTSTRAP_PROJECT_ID}}
resources:
  - name: tools-host
    type: project.py
    properties:
      billingAccountId: "{{env.CFT_BILLING_ACCOUNT_ID}}"
      parent:
        type: folder
        id: $(out.{{env.CFT_BOOTSTRAP_PROJECT_ID}}.folders.sato-folders.folders["CORE"]["name"])
      activateApis:
        - compute.googleapis.com
        - deploymentmanager.googleapis.com
        - pubsub.googleapis.com
        - container.googleapis.com
      serviceAccounts:
        - accountId: cft-demo-sa-0
          displayName: cft demo service account 0
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: false
      sharedVPCHost: true
      removeDefaultVPC: true
```
if i place `id: $(out.{{env.CFT_BOOTSTRAP_PROJECT_ID}}.folders.sato-folders.folders)` then value for id will be a map and `cft` will throw an error.
