### ISSUE TITLE
Issues when using community/cloud-foundation/templates/project/project.py

### ISSUE THREAD

**Issue by Abdennebi** [GoogleCloudPlatform/deploymentmanager-samples#363]
Hi,

1 - When I try to create a project, I'm facing the following problem:

The config file ``config.yaml``:
````yaml
imports:
  - path: templates/project/project.py
    name: project.py

resources:
  - name: <UniqueProjectName>
    type: project.py
    properties:
      parent:
        type: folder
        id: <FolderID>
      billingAccountId: <BillingAccount:ID>
      activateApis:
        - compute.googleapis.com
      serviceAccounts:
        - accountId: test-sa-1
          displayName: test service account 1
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: true
      sharedVPC: my-shared-vpc-project
      sharedVPCSubnets:
        - subnetId: shared-subnet
          region: europe-west1
````

When I run this command : 
````
gcloud deployment-manager deployments create my-deployment  --config=config.yaml
````
It says that the service account  ``PROJECT NUMBER@cloudservices.gserviceaccount.com does not exist``.

Here is the full error message
````
Waiting for create [operation-1546516005084-57e8c511f5b60-95333456-d4c56911]...failed.
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1546516005084-57e8c511f5b60-95333456-d4c56911]: errors:
- code: RESOURCE_ERROR
  location: /deployments/my-deployment/resources/add-vpc-subnet-iam-policy-1
  message: '{"ResourceType":"gcp-types/compute-beta:compute.subnetworks.setIamPolicy","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"Service    account XXXXXX16444@cloudservices.gserviceaccount.com does not exist.","reason":"invalidIamPolicy"}],"message":"Service    account XXXXXX16444@cloudservices.gserviceaccount.com does not exist.","statusMessage":"Bad
    Request","requestPath":"https://www.googleapis.com/compute/beta/projects/my-shared-vpc-project/regions/europe-west1/subnetworks/shared-subnet/setIamPolicy","httpMethod":"POST"}}'
````
When I run a second time the deployment manager (with update instead of create) the problem disapears. I think that is a dependency problem.

2- I'd like to know if that is possible to authorize a declared group to use the shared vpc like we do for the service accounts (``networkAccess: true``), for example:

````
      groups:
        - name: test-group-20190103@my-org.com
          roles:
          - roles/compute.instanceAdmin.v1
          - roles/iam.serviceAccountUser
          networkAccess: true
````

I need this because I want my users be able to create an instances using the shared VPC.

Thanks
