### ISSUE TITLE
project_creation - add to (don't override) iam-policy 

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#39]
Hi,
if I use the project_creation layout I've the following behaviour:

1. Creation with compute.googleapis.com enabled:
`  $ gcloud deployment-manager deployments create my_dm --config project.yaml`
  The project and service account <project_number>@cloudservices.gserviceaccount.com are created
2. Update the iam-policy (without manage the above service account)    
`$ gcloud deployment-manager deployments update my_dm --config project.yaml`
  The iam-policy is updated BUT the above service account <project_number>@cloudservices.gserviceaccount.com are deleted (or the role associated is revoked, i don't know)

I think the unique alternative is that, before the update step, I've to modify project.yaml and insert the relative iam policy about service account <project_number>@cloudservices.gserviceaccount.com (I don't have the project_number until the creation step and I can't refer it from the beginning because the project are not created)

The same may be usefull for the following service accounts:
- <project_number>-compute@developer.gserviceaccount.com
- service-<project_number>@container-engine-robot.iam.gserviceaccount.com
- service-<project_number>@containerregistry.iam.gserviceaccount.com
- ...

Do you have some advice for a better solution?
Thanks

**Comment by krwenholz** [comment]
Hi Davide,

I'm not sure what you mean in step 2. Could you include an example config for the IAM policies you're trying to change?

Our general recommendation is to use the project creation template to create the project and any service accounts. Then you should use a *different deployment* in the created project to manage IAM permissions and resources in that project.

**Comment by davidebelloni** [comment]
Hi,
like in your "project_creation" example (on this repo) this deployment manage also the IAM policy on the new project. I can use another deployment on the new project to manage IAM policies, but the problem about the requirement to manage google default service accounts permissions remain. And on top I think the two deployment can overwrite each other the IAM settings.

The example config you ask for may evolve from this (on project creation):

```
imports:
- path: project.py

resources:
# The "name" property below will be the name of the new project
- name: <my-project>
  type: project.py
  properties:
    ...
    iam-policy:
      bindings:
      - role: roles/iam.securityReviewer
        members:
        - group:admins@my.domain
```

to this (on project update):

```
imports:
- path: project.py

resources:
# The "name" property below will be the name of the new project
- name: <my-project>
  type: project.py
  properties:
    ...
    iam-policy:
      bindings:
      - role: roles/iam.securityReviewer
        members:
        - group:admins@my.domain
        - group:security@my.domain
```

With the update action the google default service accounts permission vanish because I don't configure explicitly the IAM policies about them.

What I would like to do is not have to handle the google default service accounts permissions on the project, i.e. permissions on the project about this accounts:
- <project_number>-compute@developer.gserviceaccount.com
- service-<project_number>@container-engine-robot.iam.gserviceaccount.com
- service-<project_number>@containerregistry.iam.gserviceaccount.com
- ...

Thank you
