### ISSUE TITLE
Spanner schema InstanceConfigs does not reflect available instance configs

### ISSUE THREAD

**Issue by jdamour98** [GoogleCloudPlatform/deploymentmanager-samples#393]
Currently, templates/cloud_spanner/cloud_spanner.py.schema offers this list as valid instance configs:

```
  instanceConfig:
    type: string
    description: The cluster location.
    enum:
      - northamerica-northeast1
      - us-central1
      - us-east1
      - us-east4
      - us-west1
      - us-west2
      - europe-north1
      - europe-west1
      - europe-west4
      - asia-south1
      - asia-east1
      - asia-northeast1
      - asia-southeast1
      - nam3
      - nam-eur-asia1
```
I ran into a few errors while trying to deploy, so i hit this api of my project to view available instanceConfigs: https://cloud.google.com/spanner/docs/reference/rest/v1/projects.instanceConfigs/list

which returns:

```
{
  "instanceConfigs": [
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/eur3",
      "displayName": "Europe (Belgium/Netherlands)"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/nam-eur-asia1",
      "displayName": "United States, Europe, and Asia (Iowa/Oklahoma/Belgium/Taiwan)"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/nam3",
      "displayName": "United States (Northern Virginia/South Carolina)"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/nam6",
      "displayName": "United States (Iowa/South Carolina/Oregon/Los Angeles)"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-asia-east1",
      "displayName": "asia-east1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-asia-east2",
      "displayName": "asia-east2"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-asia-northeast1",
      "displayName": "asia-northeast1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-asia-south1",
      "displayName": "asia-south1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-asia-southeast1",
      "displayName": "asia-southeast1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-australia-southeast1",
      "displayName": "australia-southeast1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-europe-north1",
      "displayName": "europe-north1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-europe-west1",
      "displayName": "europe-west1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-europe-west2",
      "displayName": "europe-west2"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-europe-west4",
      "displayName": "europe-west4"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-northamerica-northeast1",
      "displayName": "northamerica-northeast1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-us-central1",
      "displayName": "us-central1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-us-east1",
      "displayName": "us-east1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-us-east4",
      "displayName": "us-east4"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-us-west1",
      "displayName": "us-west1"
    },
    {
      "name": "projects/${PROJECT_ID}/instanceConfigs/regional-us-west2",
      "displayName": "us-west2"
    }
  ]
}
``` 

So the schema should be updated to use the correct names (ie. regional-us-west2 instead of us-west2). I'll open a pull request with the change
