### ISSUE TITLE
Bigquery Dataset CFT example sets unused field

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/deploymentmanager-samples#400]
One example CFT bigquery dataset  sets a field "schema" which does not seem to be parsed in the template. The field has no effect on the schema of the deployed dataset. Should it be implemented or removed?

``` 
- name: test-bq-table
    type: bigquery_table.py
    properties:
      name: test_bq_table
      datasetId: $(ref.test-bq-dataset.datasetId)
      schema:
        - name: firstname
          type: STRING
        - name: lastname
          type: STRING
        - name: age
          type: INTEGER
```

This uncovers a more sinister problem underneath... the CFT schemas are not strict, so they allow additional properties that could have no effect (or worse, the user thinks they are having an effect when in reality they are not).

I would argue each object should have `additionalProperties: false` set in the schema so unexpected fields are caught during validation. This can prevent bugs like above from slipping through.

cc @ocsig
