### ISSUE TITLE
Change hardcoded name prefixed as optional

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/deploymentmanager-samples#401]
[CloudSQL](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/cloud_sql/cloud_sql.py#L151) has hardcoded **cloud-sql** name prefix. This should be an optional parameter what a user can overwrite.

**Comment by hienle-hps** [comment]
Should the template also include non-configurable name-mangling to automatically avoid conflicts between Users and Databases on different Instances?
e.g.:

```yaml
imports:
  - path: templates/cloud_sql/cloud_sql.py
    name: cloud_sql.py

resources:
  - name: bob-blog
    type: cloud_sql.py
    properties:
      region: us-central1
      settings:
        tier: db-n1-standard-1
      users:
        - name: admin
        - name: bob
      databases:
        - name: wordpress
  - name: alice-blog
    type: cloud_sql.py
    properties:
      region: us-central1
      settings:
        tier: db-n1-standard-1
      users:
        - name: admin
        - name: alice
      databases:
        - name: wordpress
```

above example would have conflicting resource names:
* Database: `wordpress`
* User: `admin`
