### ISSUE TITLE
dependsOn RUNNING status of GCE instance

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#41]
Hi,
I'm trying to deploy a NAT gateway pool with the relative routes but I can't deploy the route when the instance have status RUNNING.

My configuration (the instanceTemplate is omitted):

```
{% for zone_natgw in properties["zones"] %}
{% set NAME_SUFFIX = zone_natgw[-2:] %}
- name: {{ IGM + NAME_SUFFIX }}
  type: compute.v1.instanceGroupManager
  properties:
    baseInstanceName: {{ env["deployment"] }}-instance
    instanceTemplate: $(ref.{{ INSTANCE_TEMPLATE }}.selfLink)
    targetSize: 1
    zone: {{ zone_natgw }}

- name: {{ MI + NAME_SUFFIX }}
  action: gcp-types/compute-v1:compute.instanceGroupManagers.listManagedInstances
  properties:
    zone: {{ zone_natgw }}
    instanceGroupManager: {{ IGM + NAME_SUFFIX }}
    project: {{ env["project"] }}
  metadata:
    dependsOn:
    - {{ IGM + NAME_SUFFIX }}

- name: {{ IR + NAME_SUFFIX }}
  type: compute.v1.route
  properties:
    network: $(ref.{{ properties["network"] }}.selfLink)
    nextHopInstance: $(ref.{{ MI + NAME_SUFFIX }}.managedInstances[0].instance)
    priority: 900
    destRange: 0.0.0.0/0
    tags:
      - to-natgw

{% endfor %}
```

I think the only solution is to use RuntimeConfig in startupscript and wait in the deployment for that resource.
Is there a better and easy way?
Thanks
