### ISSUE TITLE
cloudfoundation/gke clusters unset reference values

### ISSUE THREAD

**Issue by Chronojam** [GoogleCloudPlatform/deploymentmanager-samples#414]
Hiya.

given a config like so:

```
imports:
  - path: templates/cloud-foundation/gke/gke.py
    name: gke.py

resources:
 - name: foobar
   type: gke.py
   properties:
     zone: europe-west2-a
     cluster:
       name: foobar
       initialClusterVersion: 1.12.5-gke.5
       resourceLabels: 
         environment: production
       # Enable logging
       loggingService: logging.googleapis.com
       intialNodeCount: 1
       description: |
         A new K8s Cluster
       network: default
       subnetwork: default
       privateCluster: True
       nodeConfig:
         oauthScopes:
           - https://www.googleapis.com/auth/compute
           - https://www.googleapis.com/auth/devstorage.read_only
           - https://www.googleapis.com/auth/logging.write
           - https://www.googleapis.com/auth/monitoring
```

Creates the resource correctly, but then produces the following error:
```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1553790615076-5852a11aabfac-7a24be92-5a43673b]: errors:
- code: REFERENCE_VALUE_NOT_FOUND
  location: /deployments/project/resources/foobar->$.properties
  message: |-
    The reference 'masterAuth.clientCertificate' is not found, reason:
    The resource 'foobar' exists, but the reference value does not.
```
