### ISSUE TITLE
CFT - Can not create service project

### ISSUE THREAD

**Issue by marko7460** [GoogleCloudPlatform/deploymentmanager-samples#455]
When trying to create a service project i keep getting ```- code: CONDITION_NOT_MET
  message: Referenced resource api-compute.googleapis.com could not be found.``` error. Problem is in https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/project/project.py#L329-L331.

My yaml:
```
imports:
  - path: templates/project/project.py
    name: project.py

resources:
  - name: MY-SERVICE-PROJECT-NAME
    type: project.py
    properties:
      projectId: MY-SERVICE-PROJECT-ID
      parent:
        type: folder
        id: FOLDER-ID
      billingAccountId: BILLING-ACCOUNT
      activateApis:
        - deploymentmanager.googleapis.com
      serviceAccounts:
        - accountId: shared-network-sa
          displayName: SA has access to shared VPC
          roles:
            - roles/editor
            - roles/viewer
          networkAccess: true
      usageExportBucket: false
      removeDefaultVPC: false
      sharedVPCHost: false
      sharedVPC: HOST-PROJECT-ID
      sharedVPCSubnets:
        - subnetId: dataproc
          region: us-west1
        - subnetId: dataflow
          region: us-west1
```
