### ISSUE TITLE
Log sink and topic in different project 

### ISSUE THREAD

**Issue by tcprbs** [GoogleCloudPlatform/deploymentmanager-samples#505]
In GCP console, when a log sink export is created, there is a way to choose custom destination where the destination can be a Pub/Sub topic in another project. 

However, when I try to replicate that setup using Deployment Manager templates (Link: [here](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/logsink/logsink.py)), there seems to be no way to create the topic in another project or sink in another project. 

I tried using the project and projectId properties with another project ID but still it creates the sink and the pub/sub topic in the same DM project. 

Is there a way to accomplish this using Deployment Manager where the log sink export is created in one project and the destination is a custom one in another project?

```
resources:
- name: test-pubsub
  type: logsink.py
  properties:
    projectId: different_project
    destinationName: pubsub-topic 
    destinationType: pubsub
```

Expanded config in deployment manager for log sink shows:

```
 parent: different_project
 destination: pubsub.googleapis.com/projects/dm-project-name/topics/pubsub-topic 
``` 

Hence, my understanding is that sink should be created in different_project and pubsub be created in the same DM project for the configuration.

However the project activity shows parent being replaced by DM project name in log sink creation activity. Is there a way to avoid that?
