### ISSUE TITLE
Is enabling virtual displays supported? 

### ISSUE THREAD

**Issue by puccamau** [GoogleCloudPlatform/deploymentmanager-samples#508]
https://cloud.google.com/compute/docs/instances/enable-instance-virtual-display

**Comment by ocsig** [comment]
I never tried myself but it is art of the compute-v1 API so `type: gcp-types/compute-v1:instances` should support the property:
```yaml
properties:
    displayDevice: 
      enableDisplay: true
```

**Comment by ocsig** [comment]
I never tried it myself, but it is part of the compute-v1 API so `type: gcp-types/compute-v1:instances` should support the property:
```yaml
properties:
    displayDevice: 
      enableDisplay: true
```

Woud you mind to try to add this property to a standard windows instance deployment?
