### ISSUE TITLE
Project cannot be created because you have exceeded your allotted project quota.

### ISSUE THREAD

**Issue by imranzunzani** [GoogleCloudPlatform/deploymentmanager-samples#512]
We are using the Deployment Manager to create projects from a dedicated Project for DM under an Org Account.
From time to time we keep hitting the following error:

```
project cannot be created because you have exceeded your allotted project quota.\n type:
message: '{"ResourceType":"cloudresourcemanager.v1.project","ResourceErrorCode":"429","ResourceErrorMessage":"The
location: /deployments
```

We have tried changing the Service Account and this doesn't go away unless we switch to another project (or create a new one).
This is strange, as under the 'Quotas' we don't see anything that has exceeded the cap.
Could you please help?

**Comment by ocsig** [comment]
Project quota is the number of projects you are allowed to create within your organization. This is a bit more special then resource quotas you see under the quota page. Partially because this quota is tied to your Org/Billing account, also because deletion of the project has a [30 day grace period](https://cloud.google.com/resource-manager/docs/creating-managing-projects#shutting_down_projects) 

> At the end of the 30-day period, the project and all of its resources are deleted and cannot be recovered. Until it is deleted, the project will count towards your project quota.

I recommend you to follow the project quota increase procedures:
[Request Billing Quota Increase](https://cloud.google.com/resource-manager/docs/creating-managing-projects#managing_project_quotas)

Further explanation about [project quotas](https://support.google.com/cloud/answer/6330231?hl=en).

**Comment by imranzunzani** [comment]
We are aware of that and that quota is not exceeded.
We can create a project through
`gcloud create project`

The problem is only when using Deployment Manager.

**Comment by ocsig** [comment]
Are you able to create a new project with `gcloud` even if you are in the same project where you have the issue with DM?

**Comment by imranzunzani** [comment]
Yes

**Comment by ocsig** [comment]
The reply what you see is coming from the underlying API let me escalate this to the DM product team.
Would you mind to specify what type are you using for project creation?

**Comment by imranzunzani** [comment]
The 'type' in the config is set to 'project.py'.

**Comment by imranzunzani** [comment]
The config yaml we are using as below:

```
imports:
- path: project.py

resources:
  # The "name" property below will be the ID of the new project
  # If you want your project to have a different name, use the "project-name"
  # property.
  - name: 'project_name'
    type: project.py
    properties:
        # Change this to your organization ID.
        organization-id: 'org_id'
        # You can also create the project in a folder.
        # If both organization-id and parent-folder-id are provided,
        # the project will be created in parent-folder-id.
        parent-folder-id: 'folder_id'

        # Change the following to your organization's billing account
        billing-account-name: billingAccounts/'account_id'

        # The apis to enable in the new project.
        # To see the possible APIs, use: gcloud services list --available
        apis:
          - compute.googleapis.com
          - deploymentmanager.googleapis.com
          - pubsub.googleapis.com
          - storage-component.googleapis.com
          - monitoring.googleapis.com
          - logging.googleapis.com
          - stackdriver.googleapis.com
          - sourcerepo.googleapis.com
          - containerregistry.googleapis.com
          - cloudbuild.googleapis.com
          - container.googleapis.com
          - servicenetworking.googleapis.com

        # The service accounts you want to create in the project
        service-accounts:
          - 'sa-name'

        # Makes the service account that Deployment Manager would use in the
        # generated project when making deployments in this new project a
        # project owner.
        set-dm-service-account-as-owner: true

        # The patches to apply to the project's IAM policy. Note that these are
        # always applied as a patch to the project's current IAM policy, not as a
        # diff with the existing properties stored in DM. This means that removing
        # a binding from the 'add' section will not remove the binding on the
        # project during the next update. Instead it must be added to the 'remove'
        # section.
        iam-policy-patch:
            # These are the bindings to add.
            add:
              - role: roles/owner
                members:
                  - group:'google-group-account'
              - role: roles/viewer
                members:
                  - 'viewer-sa'
              - role: roles/editor
                members: 
                  - 'editor-sa'
```
