### ISSUE TITLE
Create a Google App Engine Flexible sample

### ISSUE THREAD

**Issue by greggdonovan** [GoogleCloudPlatform/deploymentmanager-samples#54]
There are no examples for Google AppEngine Flex. We'd like to provision a particular GAE app for all instances of a project type and don't have much in the way of docs or examples to go on.

**Comment by krwenholz** [comment]
Hi Greg,

Turns out this is more difficult than expected. We're working on a sample and will update here when it's available, which may be another week or two depending on priorities.

Our non-working prototype (assuming the AppEngine Flex and Admin APIs have been enabled):

```yaml
resources:
- type: appengine.v1beta4.version
  name: my-cool-service
  properties:
    modulesId: default
    appsId: PROJECT_NAME
    runtime: custom-runtimes
    env: flex
    manualScaling:
      instances: 1
    deployment:
      container:
        image: "gcr.io/SOME_CONTAINER"
    handlers:
      - script:
          scriptPath: "main.app"
        securityLevel: "SECURE_OPTIONAL"
        urlRegex: "/"
    threadsafe: true
```

This sample appears to create a GAE flex version successfully but actually booting it up fails for several container images we have tried. I was working off the discovery doc found [here](https://www.googleapis.com/discovery/v1/apis/appengine/v1beta4/rest) as a reference. If you manage to get something working or need help let us know. We'll try to a working sample up soon though.

Thanks.

**Comment by greggdonovan** [comment]
@krwenholz Thanks so much for looking into it!

**Comment by krwenholz** [comment]
Hi Greg,

That sample is still as far as we've gotten. The AppEngine APIs don't lend themselves to a declarative configuration like DM, so we're struggling to piece together a reliable process. Your best option at this point might be to look into using Cloud Container Builder to run gcloud commands for managing your app. You could use this separately or in conjunction with DM. We have a sample of running a build with DM [here](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/cloudbuild).

We have an internal bug to work out how we want to integrate with AppEngine but it's a bigger beast than we would like. Staffing it probably won't happen until Q2 2018.

If you happen to make any progress on your own and need some help, feel free to reach out here.

I'll leave this bug open until we close the internal bug and to provide any updates we may have.

**Comment by salrashid123** [comment]
@krwenholz   i thin you pretty much have/had it right. 

- first build the app and push it to your gcr registry:
```
$ docker build -t us.gcr.io/your_project/appengine/default.mydmapp .
$ gcloud docker -- push us.gcr.io/your_project/appengine/default.mydmapp
```

deploy.jinja:

```yaml
resources:
- type: appengine.v1.version
  name: my-cool-service
  properties:
    servicesId: default
    appsId: your_project
    runtime: custom
    env: flex
    manualScaling:
      instances: 1
    deployment:
      container:
        image: "us.gcr.io/your_project/appengine/default.mydmapp"
    handlers:
      - script:
          scriptPath: "main.app"
        securityLevel: "SECURE_OPTIONAL"
        urlRegex: "/"
    threadsafe: true
```

- deploy
```
$ gcloud deployment-manager deployments create flex --template deploy.jinja 
The fingerprint of the deployment is 9kfK4aj6z72DJMb0GOLWww==
Waiting for create [operation-1510815958295-55e144083e1d9-0cc3e6f3-fd8c0009]...done.                                                                                                                              
Create operation operation-1510815958295-55e144083e1d9-0cc3e6f3-fd8c0009 completed successfully.
NAME             TYPE                  STATE      ERRORS  INTENT
my-cool-service  appengine.v1.version  COMPLETED  []
```
- verify

```
$ curl https://my-cool-service-dot-mineral-minutia-820.appspot.com/
hello world
```


---

- app.yaml
```yaml
runtime: custom
env: flex
network:
  name: default
manual_scaling:
  instances: 1
```

- Dockerfile 
```dockerfile
FROM python:2.7-slim
ADD . /app
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/gunicorn", "-b", ":8080", "main:app"] 
```

- requirements.txt 
```
Flask==0.10.1
gunicorn==19.3.0
```

- main.py 
```python
from flask import Flask

import logging

app = Flask(__name__)

@app.route('/', methods = ['GET'])
def index():
    logging.info("/ called")
    return 'hello world', 200, {'Content-Type': 'text/plain; charset=utf-8'}

@app.route('/_ah/health')
def healthcheck():
    return 'ok', 200, {'Content-Type': 'text/plain; charset=utf-8'}

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
```

**Comment by krwenholz** [comment]
Thanks @salrashid123! That would work for the first version, but I'm not sure it works for subsequent versions where you might want to split/migrate traffic, avoid overwriting versions, etc. We should probably evolve the sample to do all of that before publishing. Or does it work for those things already? I'm not very familiar with AppEngine beyond the issues I ran into trying to get a sample working.

**Comment by salrashid123** [comment]
you're right, traffic splitting and versioning doesn't happen with just the ```appengine.v1.version``` provider that is exposed right now.

we need
```apps.services```  collection for that
see [migrating_or_splitting_traffic](https://cloud.google.com/appengine/docs/admin-api/migrating-splitting-traffic#migrating_or_splitting_traffic)


```
$ gcloud deployment-manager types list --project gcp-types  | grep app
appengine.v1.version
```
- and its not on our [supported-resource-types](https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types)

**Comment by krwenholz** [comment]
Ah okay thanks for the clarification @salrashid123. We'll keep an eye on that other collection if we decide to add full support for AppEngine (still a ways out if we do).

**Comment by greggdonovan** [comment]
Thanks for the help @krwenholz and @salrashid123!

**Comment by krwenholz** [comment]
Hi @greggdonovan,

We had a long chat about this today and decided AppEngine support is unlikely to land in DM this year. There are some fundamental gaps between their API and our interaction model requiring significant work to make a sane user experience. We'll reevaluate this again in the future, but for now I'm going to close this issue to avoid creating a false sense of hope. Sorry for the bad news.

Best,

Kyle

**Comment by greggdonovan** [comment]
@krwenholz Thanks for letting me know -- much appreciated!

**Comment by raphaelarias** [comment]
Any updates?

**Comment by salrashid123** [comment]
Looks like the `services` its in the beta type provider.

```
 gcloud beta deployment-manager types list --project gcp-types  | grep -A 20 -B 20 appengine
```

```yaml
provider: gcp-types/appengine-v1
types:
- apps
- apps.locations
- apps.authorizedCertificates
- apps.services
- apps.services.versions
- apps.services.versions.instances
- apps.authorizedDomains
- apps.operations
- apps.domainMappings
- apps.firewall.ingressRules
```
maybe able to do splitting using the `services.verison` now
- https://cloud.google.com/appengine/docs/admin-api/reference/rpc/google.appengine.v1#versions

**Comment by aniket-cloud** [comment]
Hi,

As per your guidance, we can deploy app successfully via deployment manager in flexible environment using docker image from container registry. But if I need to deploy app in standard environment and from local directory, not from container registry. Then how it will be possible.

Please guide to resolve the issue.

Thank You.

**Comment by jliukai** [comment]
see https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions for flexible and standard

ie.
resources:
  - name: cool-app-name
    type: appengine.v1.version
    properties:
      appsId: <project id>
      servicesId: default
      instanceClass: F1
      runtime: go113
      env: standard
      threadsafe: true

**Comment by bkanuka** [comment]
Hey - sorry for bringing up an old bug, but this thread is high up on Google when searching for issues with App Engine Flex and Deployment Manager. 

Just a tip, that App Engine Flexible needs a couple APIs enabled before it will deploy properly using DM (and I dont see this documented anywhere).  You need to enable:

- appengine.googleapis.com
- appengineflex.googleapis.com
- compute.googleapis.com

and of course you can do this in your deployment using the following:

```
  - type: deploymentmanager.v2.virtual.enableService
    name: enable-api-appengine
    properties:
      consumerId: "project:{{ env['project'] }}"
      serviceName: appengine.googleapis.com

  - type: deploymentmanager.v2.virtual.enableService
    name: enable-api-appengineflex
    properties:
      consumerId: "project:{{ env['project'] }}"
      serviceName: appengineflex.googleapis.com

  - type: deploymentmanager.v2.virtual.enableService
    name: enable-api-compute
    properties:
      consumerId: "project:{{ env['project'] }}"
      serviceName: compute.googleapis.com
```
