### ISSUE TITLE
Set redis config parameters.

### ISSUE THREAD

**Issue by kanekv** [GoogleCloudPlatform/deploymentmanager-samples#554]
I have tried to add custom redis config like this:
```
### Redis instance
- name: cache
  type: gcp-types/redis-v1:projects.locations.instances
  properties:
    parent: projects/{{ env["project"] }}/locations/us-central1
    instanceId: cache
    authorizedNetwork: projects/{{ env["project"] }}/global/networks/default
    memorySizeGb: 1
    tier: BASIC
    redisConfigs:
      "maxmemory-policy": "allkeys-lru" # TODO: this doesn't work for some reason
```

Doesn't seem like it's taking `redisConfigs` into account. Is it possible to set it with DM?
