### ISSUE TITLE
Creating a DNS managedZone returns "INVALID_ARGUMENT"

### ISSUE THREAD

**Issue by jimanvlad** [GoogleCloudPlatform/deploymentmanager-samples#555]
Hi,

I am trying to create a managed DNS zone following the example [here](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/google/resource-snippets/dns-v1/managed-zone.yaml) and I get the following error in Deployment Manager:
```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1588969909552-5a528e3048557-8403a662-67474853]: errors:
- code: RESOURCE_ERROR
  location: /deployments/dev-server/resources/YOUR_DEPLOYMENT_NAME
  message: '{"ResourceType":"dns.v1.managedZone","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Request
    contains an invalid argument.","status":"INVALID_ARGUMENT","statusMessage":"Bad
    Request","requestPath":"https://dns.googleapis.com/dns/v1/projects/mygcpproject/managedZones","httpMethod":"POST"}}'
```

Code:
```
resources:
- name: YOUR_DEPLOYMENT_NAME
  type: gcp-types/dns-v1:managedZones
  properties:
    description: A managed zone
# Making dnsName unique with deployment name for testing purpose.
    dnsName: my-great-domain-YOUR_DEPLOYMENT_NAME.com.
```

I also tried with `type: dns.v1.managedZone` as well as type:  `gcp-types/dns-v1beta2:managedZones`. I get the same exact same error regardless of the properties that I add.

I can create the managed zone via the Console, gcloud command as well as pinging the REST API manually. Just not with Depoyent Manager.
