### ISSUE TITLE
sqladmin.v1beta4.database on an existing DB

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#59]
Hi,
I'm trying to manage an existing CloudSQL database with DM.
My config is:

```
-  type: sqladmin.v1beta4.database
   name: db-test-mysql-dbname
   properties:
     instance: $(ref.db-test-mysql.name)
     name: dbname
     charset: utf8
     collation: utf8_general_ci
     project: <mi_project>
   metadata:
     dependsOn:
     - db-test-mysql
```

and I've the following error after :

```
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1509978536738-55d51464cfcd0-f415ec62-9971347b]: errors:
- code: RESOURCE_ERROR
  location: /deployments/resources/resources/db-test-mysql-dbname
  message: '{"ResourceType":"sqladmin.v1beta4.database","ResourceErrorCode":"INTERNAL_ERROR","ResourceErrorMessage":""}'
```

Where is the issue? I can't understand the problem.

**Comment by adamharwayne** [comment]
Hi,

It appears that the sqladmin API sent an INTERNAL_ERROR response to DM's insert request. 

If the error code seen in DM's API is 'RESOURCE_ERROR', then that means DM is proxying the error from the underlying API, not creating the error itself.

Can you see any errors in the Cloud Console Logging page? Specifically for a Cloud SQL Database in the timespan of that operation?

**Comment by davidebelloni** [comment]
Hi,
yes I've it:

```
---
insertId: 55D51D004B1C1.A9814E5.1C0ECCC7
logName: projects/<project>/logs/cloudaudit.googleapis.com%2Factivity
protoPayload:
  '@type': type.googleapis.com/google.cloud.audit.AuditLog
  authenticationInfo:
    principalEmail: <project_id>@cloudservices.gserviceaccount.com
  authorizationInfo:
  - authorizationLoggingOptions:
      permissionType: ADMIN_WRITE
    granted: true
    permission: cloudsql.instances.create
    resource: instances/<project>:db-test-mysql
  methodName: cloudsql.instances.create
  request:
    '@type': type.googleapis.com/cloudsql.admin.InstancesInsertRequest
    clientIp: 10.94.34.4
    resource:
      backendType: SECOND_GEN
      databaseVersion: MYSQL_5_6
      failoverReplica:
        available: false
      instanceName:
        fullProjectId: <project>
        instanceId:db-test-mysql
      instanceType: CLOUDSQL_INSTANCE
      region: australia-southeast1
      settings:
        activationPolicy: ALWAYS
        backupConfig:
          binaryLogEnabled: true
          enabled: true
          specification: every day 13:00
        dataDiskSizeGb: '10'
        dataDiskType: PD_SSD
        ipConfiguration:
          enabled: true
          requireSsl: true
        labels:
        - key: hex
          value: 7ce691c82ba3
        locationPreference:
          gceZone: australia-southeast1-a
        maintenanceWindow:
          dayOfWeek: 2
          hourOfDay: 17
        storageAutoResize: true
        storageAutoResizeLimit: '100'
        tier: db-g1-small
  requestMetadata:
    callerIp: 0.1.0.1
  resourceName: instances/<project>:db-test-mysql
  response:
    '@type': type.googleapis.com/cloudsql.admin.InstancesInsertResponse
  serviceName: cloudsql.googleapis.com
  status:
    code: 2
    message: UNKNOWN
receiveTimestamp: '2017-11-06T15:07:28.438225330Z'
resource:
  labels:
    database_id: <project>:db-test-mysql
    project_id: <project>
    region: australia-southeast1
  type: cloudsql_database
severity: ERROR
timestamp: '2017-11-06T15:07:27.231Z'
```
