### ISSUE TITLE
Invalid value for field 'resource.networkInterfaces': ''. Updating 'networkInterface' is not supported

### ISSUE THREAD

**Issue by valyala** [GoogleCloudPlatform/deploymentmanager-samples#630]
We successfully use deployment manager since 2018 for deploying an infrastructure with multiple subnetworks, many instances and Docker apps inside these instances. Today the deployment manager started returning the following error during the deployment:

```
Invalid value for field 'resource.networkInterfaces': ''. Updating 'networkInterface' is not supported
```

The full error message:

```json
{
  "ResourceType": "compute.v1.instance",
  "ResourceErrorCode": "400",
  "ResourceErrorMessage": {
    "code": 400,
    "errors": [
      {
        "domain": "global",
        "    message": "Invalid value for field 'resource.networkInterfaces': ''. Updating     'networkInterface' is not supported.",
        "reason": "invalid"
      }
    ],
    "message": "Invalid value for field 'resource.networkInterfaces': ''. Updating 'networkInterface'     is not supported.",
    "statusMessage": "Bad Request",
    "requestPath": "https://compute.googleapis.com/compute/v1/projects/xxx/zones/us-east1-b/instances/yyy",
    "httpMethod": "PUT"
  }
}
```

The request body for the corresponding `PUT` request:

```yml
  name: yyy
  properties:
    disks:
    - autoDelete: true
      boot: true
      deviceName: boot
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/cos-cloud/global/images/family/cos-stable
      type: PERSISTENT
    machineType: https://www.googleapis.com/compute/v1/projects/xxx/zones/us-east1-b/machineTypes/f1-micro
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/xxx/global/networks/default
      subnetwork: $(ref.zzz.selfLink)
    serviceAccounts:
    - email: default
      scopes:
      - https://www.googleapis.com/auth/devstorage.read_write
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring.write
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/service.management.readonly
    zone: us-east1-b
  type: compute.v1.instance
```

This request body wasn't modified during the last year.
