### ISSUE TITLE
Bucket creation in different project from "DM Creation Project"

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#78]
Hi,
I've some issues creating bucket from the "DM Creation Project" in the new project.

The expanded config are something like that (simplified) :

```
- metadata:
    dependsOn:
    - project
    - storage-component.googleapis.com
    - patch-iam-policy
  name: log-$(ref.project.projectNumber)
  properties:
    name: log-$(ref.project.projectNumber)
    project: $(ref.project.projectId)
  type: gcp-types/storage-v1:buckets
```

The resulting bucket is created in the "DM Creation Project" and not in the "ref.project.projectId". The same is for log sink :

```
- metadata:
    dependsOn:
    - project
    - log-$(ref.project.projectNumber)
  name: log-sink-log-$(ref.project.projectNumber)
  properties:
    destination: storage.googleapis.com/log-$(ref.project.projectNumber)
    filter: ''
    parent: projects/$(ref.project.projectId)
    sink: log-sink-log-$(ref.project.projectNumber)
    uniqueWriterIdentity: true
  type: logging.v2.sink
```

My use case is to create a default bucket for exported logs of the new project.

Thanks

**Comment by adamharwayne** [comment]
I've updated the configuration for gcp-types/storage-v1:buckets, it should now allow creation in a different project. 

I'm still working on logging.v2.sink.

**Comment by davidebelloni** [comment]
Hi,
what do you mean with "I've updated the configuration for gcp-types/storage-v1:buckets"?

I can't see new commits

Thanks

**Comment by adamharwayne** [comment]
I altered the configuration of the storage-v1 type provider, so it should work with your existing configurations. The type provider is contained within DM, so doesn't publish any commits to Github.

I tested using the following configuration:

```
resources:
- name: my-bucket
  type: gcp-types/storage-v1:buckets
  properties:
    name: log-1234-different-project
    project: different-project
- name: my-bucket-2
  type: gcp-types/storage-v1:buckets
  properties:
    name: log-1234-deploying-project
```

And verified that 'log-1234-different-project' was created in 'different-project', while 'log-1234-deploying-project' was created in the project that contained the deployment.

**Comment by adamharwayne** [comment]
I just pushed an update to gcp-types/logging-v2:projects.sinks and gcp-types/logging-v2:projects.metrics. They should now both be capable of being created in a different project. I have not updated logging.v2.sink. I recommend switching over to gcp-types/logging-v2:projects.sinks.

I tested using the following configuration:

```
resources:
- name: same-project-sink
  type: gcp-types/logging-v2:projects.sinks
  properties:
    sink: same-project-sink
    destination: pubsub.googleapis.com/projects/same-project/topics/a-topic
    filter: severity >= ERROR
    outputVersionFormat: V2
- name: same-project-metric
  type: gcp-types/logging-v2:projects.metrics
  properties:
    metric: same-project-metric
    filter: severity >= ERROR
- name: diff-project-sink
  type: gcp-types/logging-v2:projects.sinks
  properties:
    sink: diff-project-sink
    project: different-project
    destination: pubsub.googleapis.com/projects/different-project/topics/a-topic
    filter: severity >= ERROR
    outputVersionFormat: V2
- name: diff-project-metric
  type: gcp-types/logging-v2:projects.metrics
  properties:
    metric: diff-project-metric
    project: different-project
    filter: severity >= ERROR
```
