### ISSUE TITLE
GKE Nodepool update BestPractice

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#79]
Hi,
I've created a GKE cluster with container.v1.cluster, 1 default node with container.v1.nodePool and minimum 2 (for HA) custom node with container.v1.nodePool.

This setup permit to update the custom nodepool creating a new one, cordon and drain the old nodes and finally remove the old custom nodepool.

I wonder if there's a way to obtain this features and behaviour without the 1 default node container.v1.nodePool (VM not needed)

Thanks

**Comment by davidebelloni** [comment]
Hi,
do you have some feedback about this request?

Thanks

**Comment by munutzer** [comment]
Hi Davide,
Could you share your DM template or a similar one with me? Or describe the cluster resource (does it have the nodePools resource property set?) and the three (?) container.v1.nodePool resources? How does the default container.v1.nodePool resource differ from the custom node pools, and do you need to create it in the first place?
Thanks

**Comment by davidebelloni** [comment]
Hi,
I understand that I explained myself quite bad.

My initial resources for GKE are:
```
- name: {{ GKE_CLUSTER }}
  type: container.v1.cluster
  properties:
    zone: europe-west3-a
    cluster:
      name: {{ GKE_CLUSTER }}
      initialClusterVersion: 1.8.5-gke.0
      initialNodeCount: 1
      locations:
      - europe-west3-a
      enableKubernetesAlpha: false
      masterAuth:
        username: ''
        clientCertificateConfig:
          issueClientCertificate: false
      legacyAbac:
        enabled: false
      networkPolicy:
        provider: CALICO
        enabled: true
      addonsConfig:
        httpLoadBalancing:
          disabled: false
        horizontalPodAutoscaling:
          disabled: false
        kubernetesDashboard:
          disabled: true
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: $(ref.net.name)
      clusterIpv4Cidr: 10.32.0.0/14
      subnetwork: $(ref.net-europe-west3.name)

- name: {{ GKE_CLUSTER }}-test1
  type: container.v1.nodePool
  properties:
    zone: europe-west3-a
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePool:
      name: {{ GKE_CLUSTER }}-test1
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-4096
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com
```

If I want to modify the nodePool (for example extending the RAM) I can:

STEP1 - Add {{ GKE_CLUSTER }}-test2 NodePool

```
- name: {{ GKE_CLUSTER }}
  type: container.v1.cluster
  properties:
    zone: europe-west3-a
    cluster:
      name: {{ GKE_CLUSTER }}
      initialClusterVersion: 1.8.5-gke.0
      initialNodeCount: 1
      locations:
      - europe-west3-a
      enableKubernetesAlpha: false
      masterAuth:
        username: ''
        clientCertificateConfig:
          issueClientCertificate: false
      legacyAbac:
        enabled: false
      networkPolicy:
        provider: CALICO
        enabled: true
      addonsConfig:
        httpLoadBalancing:
          disabled: false
        horizontalPodAutoscaling:
          disabled: false
        kubernetesDashboard:
          disabled: true
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: $(ref.net.name)
      clusterIpv4Cidr: 10.32.0.0/14
      subnetwork: $(ref.net-europe-west3.name)

- name: {{ GKE_CLUSTER }}-test1
  type: container.v1.nodePool
  properties:
    zone: europe-west3-a
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePool:
      name: {{ GKE_CLUSTER }}-test1
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-4096
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com

- name: {{ GKE_CLUSTER }}-test2
  type: container.v1.nodePool
  properties:
    zone: europe-west3-a
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePool:
      name: {{ GKE_CLUSTER }}-test2
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-8192
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com
```

STEP2 - Cordon and drain the "{{ GKE_CLUSTER }}-test1" nodes 

STEP3 - Remove {{ GKE_CLUSTER }}-test1 NodePool

```
- name: {{ GKE_CLUSTER }}
  type: container.v1.cluster
  properties:
    zone: europe-west3-a
    cluster:
      name: {{ GKE_CLUSTER }}
      initialClusterVersion: 1.8.5-gke.0
      initialNodeCount: 1
      locations:
      - europe-west3-a
      enableKubernetesAlpha: false
      masterAuth:
        username: ''
        clientCertificateConfig:
          issueClientCertificate: false
      legacyAbac:
        enabled: false
      networkPolicy:
        provider: CALICO
        enabled: true
      addonsConfig:
        httpLoadBalancing:
          disabled: false
        horizontalPodAutoscaling:
          disabled: false
        kubernetesDashboard:
          disabled: true
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: $(ref.net.name)
      clusterIpv4Cidr: 10.32.0.0/14
      subnetwork: $(ref.net-europe-west3.name)

- name: {{ GKE_CLUSTER }}-test2
  type: container.v1.nodePool
  properties:
    zone: europe-west3-a
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePool:
      name: {{ GKE_CLUSTER }}-test2
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-8192
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com
```

Do you think is the best approach?

Thanks

**Comment by davidebelloni** [comment]
Hi @munutzer ,
do you have some suggestions about this issue?

Thanks

**Comment by munutzer** [comment]
Hi Davide,

When you create the cluster resource, duplicate the first nodePool config in the cluster.nodePools resource property.

So the initial resource config would look something like:
```
- name: {{ GKE_CLUSTER }}
  type: container.v1.cluster
  properties:
    zone: europe-west3-a
    cluster:
      name: {{ GKE_CLUSTER }}
      initialClusterVersion: 1.8.5-gke.0
      initialNodeCount: 1
      nodePools:
        name: {{ GKE_CLUSTER }}-test1
  type: container.v1.nodePool
  properties:
    zone: europe-west3-a
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePools:
    - name: {{ GKE_CLUSTER }}-test1
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-4096
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com
      locations:
      - europe-west3-a
      enableKubernetesAlpha: false
      masterAuth:
        username: ''
        clientCertificateConfig:
          issueClientCertificate: false
      legacyAbac:
        enabled: false
      networkPolicy:
        provider: CALICO
        enabled: true
      addonsConfig:
        httpLoadBalancing:
          disabled: false
        horizontalPodAutoscaling:
          disabled: false
        kubernetesDashboard:
          disabled: true
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: $(ref.net.name)
      clusterIpv4Cidr: 10.32.0.0/14
      subnetwork: $(ref.net-europe-west3.name)

- name: {{ GKE_CLUSTER }}-test1
  type: container.v1.nodePool
  properties:
    zone: europe-west3-a
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePool:
      name: {{ GKE_CLUSTER }}-test1
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-4096
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com
```

A cluster must have at least one nodePool when it is created. By including your first custom nodePool in the cluster resource config, you will avoid GKE adding a default-pool.
In subsequent updates, leave the cluster config as-is (including that first node pool - don't remove the cluster.nodePools config even if you delete the corresponding container.v1.nodePools resource).

**Comment by davidebelloni** [comment]
Hi,
your configuration doesn't work for me.

I can create a Cluster with 0 node with the following (magic for me!):
```
- name: {{ GKE_CLUSTER }}
  type: container.v1.cluster
  properties:
    zone: europe-west4-c
    cluster:
      name: {{ GKE_CLUSTER }}
      initialClusterVersion: 1.8.5-gke.0
      nodePools:
      - name: {{ GKE_CLUSTER }}-test1
      locations:
      - europe-west4-c
      enableKubernetesAlpha: false
      masterAuth:
        username: ''
        clientCertificateConfig:
          issueClientCertificate: false
      legacyAbac:
        enabled: false
      networkPolicy:
        provider: CALICO
        enabled: true
      addonsConfig:
        httpLoadBalancing:
          disabled: false
        horizontalPodAutoscaling:
          disabled: false
        kubernetesDashboard:
          disabled: true
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: $(ref.net.name)
      clusterIpv4Cidr: 10.32.0.0/14
      subnetwork: $(ref.net-europe-west4.name)
- name: {{ GKE_CLUSTER }}-test1
  type: container.v1.nodePool
  properties:
    zone: europe-west4-c
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePool:
      name: {{ GKE_CLUSTER }}-test1
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-4096
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com
```

But when I create a new "{{ GKE_CLUSTER }}-test2" I've the following warning: "Pods unschedulable"
No pods running on the unique VM GCE created (note there is autoscaling enabled) and this VM is not visible under cluster nodes.

If I remove "{{ GKE_CLUSTER }}-test2" NodePool and create a new " {{ GKE_CLUSTER }}-test3" Nodepool the deployment finish correctly in something like 10-15 minutes, with the final results similar to the above step.

Any suggestion?
Thanks!

**Comment by munutzer** [comment]
In your config above, is the test1 node pool using your custom config (machineType, etc)? If not, you may need to duplicate the entire config (everything under 'nodePool' on the node pool resource) in the cluster.nodePools property.

I haven't seen the "Pods unschedulable" error before. What is the difference between test2 node pool that doesn't work and test3 that does?

**Comment by davidebelloni** [comment]
Hi @munutzer ,
In the above tests either test2 and test3 doesn't work and test1 node pool is using my custom config.

Duplicating the entire config in the cluster.nodePools property and creating a new deployment generate a cluster with the test1 node pool and all the pods scheduled on a single node
Here the initial configuration:

```
- name: {{ GKE_CLUSTER }}
  type: container.v1.cluster
  properties:
    zone: europe-west4-c
    cluster:
      name: {{ GKE_CLUSTER }}
      initialClusterVersion: 1.8.5-gke.0
      nodePools:
      - name: {{ GKE_CLUSTER }}-test1
        initialNodeCount: 1
        autoscaling:
          enabled: true
          minNodeCount: 1
          maxNodeCount: 3
        management:
          autoUpgrade: true
          autoRepair: true
        config:
          machineType: custom-2-4096
          diskSizeGb: 20
          preemptible: false
          imageType: COS
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring
          - https://www.googleapis.com/auth/cloud_debugger
          localSsdCount: 0
          serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com
      locations:
      - europe-west4-c
      enableKubernetesAlpha: false
      masterAuth:
        username: ''
        clientCertificateConfig:
          issueClientCertificate: false
      legacyAbac:
        enabled: false
      networkPolicy:
        provider: CALICO
        enabled: true
      addonsConfig:
        httpLoadBalancing:
          disabled: false
        horizontalPodAutoscaling:
          disabled: false
        kubernetesDashboard:
          disabled: true
      loggingService: logging.googleapis.com
      monitoringService: monitoring.googleapis.com
      network: $(ref.net.name)
      clusterIpv4Cidr: 10.32.0.0/14
      subnetwork: $(ref.net-europe-west4.name)

- name: {{ GKE_CLUSTER }}-test1
  type: container.v1.nodePool
  properties:
    zone: europe-west4-c
    clusterId: $(ref.{{ GKE_CLUSTER }}.name)
    nodePool:
      name: {{ GKE_CLUSTER }}-test1
      initialNodeCount: 1
      autoscaling:
        enabled: true
        minNodeCount: 1
        maxNodeCount: 3
      management:
        autoUpgrade: true
        autoRepair: true
      config:
        machineType: custom-2-4096
        diskSizeGb: 20
        preemptible: false
        imageType: COS
        oauthScopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloud_debugger
        localSsdCount: 0
        serviceAccount: svc-{{ GKE_CLUSTER }}@{{ env['project'] }}.iam.gserviceaccount.com

```

In this test when I remove test1 node pool resource (not from cluster.nodePools) and create a new test2 node pool resource I've that the deployment finish correctly in something like 20 minutes with a VM created but not linked to the cluster and with the final results of "Pods unschedulable".

I can't understand:

- why my test ends in this state?
- the need of nodePool resources if I replicate the configuration in cluster.nodePools resource, what is the principle?
- when I add a new nodePool resource I have to replicate always the configuration in cluster.nodePools resource adding an item to that list?

Thanks

**Comment by munutzer** [comment]
> why my test ends in this state?
I don't know. I do not get the same error when I try to repro (using similar config but no serviceAccount property and a standard machine type). When you create test2 nodePool, can you see that node pool in the GKE API (node-pools list), or do you only see the corresponding GCE VM? Do you have any additional information that could help me reproduce and debug the error?

> the need of nodePool resources if I replicate the configuration in cluster.nodePools resource, what is the principle?
DM handles updates by diffing your new and old configuration resource lists. Typically we would only issue a delete request if a resource is removed from the config. Node pool configs as a cluster property (rather than a separate resource in the config) don't fit well with this model. So typically I would recommend that you use separate node pool resources so that you can delete the node pool resource in the config and DM will know to delete the node pool rather than modify the cluster resource somehow.

However, you don't want a default node pool. By putting the first node pool config in the cluster resource properties, DM will pass that node config in the cluster create request (so it is created *instead* of a default pool). When it goes to create the next resource in the config (test1 nodepool), it will realize there is already a resource with that name, so no need to issue a second create request.
The reason to still add a container.v1.nodePool resource in the DM config is so that you can modify or delete the node pool in your config later without changing the cluster resource.

> when I add a new nodePool resource I have to replicate always the configuration in cluster.nodePools resource adding an item to that list?
No. Generally I'd recommend using separate nodePool resources instead. Duplicating the first node pool config in the cluster.nodePools properties is done only to avoid creating a default node pool as part of the cluster create request.

**Comment by davidebelloni** [comment]
Hi @munutzer,
I've understood where I was in fault: what do you suggest works if the update to DM doesn't remove all the nodepools by cluster.

If i made an atomic change where I add a new nodepool and remove the old one and apply that deployment, than occur the issue exposed above. If I do the same operation with a survivor nodepool (from two nodepools I remove one of these and add a new nodepool) there's no problems.

Thanks

**Comment by davidebelloni** [comment]
Hi @munutzer 
now I've the following problem with this setup

After the above resources I've :

```
- type: compute.v1.route
  name: static-to-{{ GKE_CLUSTER }}-master
  properties:
    network: $(ref.net.selfLink)
    nextHopGateway: projects/{{ env['project'] }}/global/gateways/default-internet-gateway
    priority: 2000
    destRange: $(ref.{{ GKE_CLUSTER }}.endpoint)/32
    tags:
      - "{{ GKE_CLUSTER }}-tag"
```

This worked great with the single self-contained resource container.v1.cluster, but with the container.v1.cluster + container.v1.nodePool resources this give me the following error:

```
$ gcloud deployment-manager deployments update resources --project "$DMPROJECT" --config resources.yaml 
The fingerprint of the deployment is cDlTQgF2_jIHTMKnO46EMA==
Waiting for update [operation-1519129867395-565a3fc1d1fb8-afdb98f4-c234223d]...failed.                                                                                                                                                                                                                                       
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1519129867395-565a3fc1d1fb8-afdb98f4-c234223d]: errors:
- code: REFERENCE_VALUE_NOT_FOUND
  location: /deployments/resources/resources/gke->$.properties
  message: |-
    The reference 'endpoint' is not found, reason:
    The resource 'gke' exists, but the reference value does not.
```

It seems that the GKE cluster is not ready (doesn't have endpoint value) when the container.v1.cluster is deployed. And I wouldn't create a dependency in compute.v1.route resource from container.v1.nodePool because it will be a dynamic resource that will change in the future.

Any suggestion?
Thanks
