### ISSUE TITLE
listManagedInstances in nextHopInstance route parameter

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/deploymentmanager-samples#84]
Hi,
I've the following code:

```
- name: nat-gw-it
  properties:
    properties:
      canIpForward: true
      disks:
      - autoDelete: true
        boot: true
        deviceName: boot
        initializeParams:
          sourceImage: https://www.googleapis.com/compute/v1/projects/<my_image_path>
        type: PERSISTENT
      machineType: f1-micro
      networkInterfaces:
      - accessConfigs:
        - name: External-IP
          type: ONE_TO_ONE_NAT
        network: $(ref.my-net.selfLink)
        subnetwork: $(ref.my-net-australia-southeast1-natgw.selfLink)
      scheduling:
        automaticRestart: true
        onHostMaintenance: MIGRATE
        preemptible: false
      serviceAccounts:
      - email: my-svc@<my_project>.iam.gserviceaccount.com
        scopes:
        - https://www.googleapis.com/auth/compute
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/cloudruntimeconfig
      tags:
        items:
        - natgw
    zone: australia-southeast1-a
  type: compute.v1.instanceTemplate
  metadata:
    dependsOn:
    - my-net
    - my-net-australia-southeast1-natgw
- name: nat-gw-igm-a
  properties:
    baseInstanceName: nat-gw-instance
    instanceTemplate: $(ref.nat-gw-it.selfLink)
    targetSize: 1
    zone: australia-southeast1-a
  type: compute.v1.instanceGroupManager
  metadata:
    dependsOn:
    - nat-gw-it
- action: gcp-types/compute-v1:compute.instanceGroupManagers.listManagedInstances
  metadata:
    dependsOn:
    - nat-gw-igm-a
  name: nat-gw-mi-a
  properties:
    instanceGroupManager: nat-gw-igm-a
    project: <my_project>
    zone: australia-southeast1-a
- metadata:
    dependsOn:
    - my-net
    - nat-gw-mi-a
  name: nat-gw-route-a
  properties:
    destRange: 0.0.0.0/0
    network: $(ref.my-net.selfLink)
    nextHopInstance: $(ref.nat-gw-mi-a.managedInstances[0].instance)
    priority: 900
    tags:
    - to-natgw
  type: compute.v1.route
```

In the past months (weeks?) this works great. 
Now I've delete the deployment (with --delete-policy=abandon) and recreated, but I've the folowing error:

```
The fingerprint of the deployment is wdvBVr6JNMij4oDxck0Qdw==
Waiting for update [operation-1517232148895-563ea2346d518-ee36a40a-e14c3f5e]...failed.                                                                                                                                                                                                                                     
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1517232148895-563ea2346d518-ee36a40a-e14c3f5e]: errors:
- code: CONDITION_NOT_MET
  location: /deployments/resources/resources/nat-gw-route-a->$.properties
  message: '"/nextHopInstance": domain: validation; keyword: type; message: instance
    does not match any allowed primitive type; allowed: ["string"]; found: "null"'
```

Is changed something? I can't understand what I'm ding wrong.

Thanks
