### ISSUE TITLE
Unable to use name property in gcp-types/sqladmin-v1beta4:users

### ISSUE THREAD

**Issue by dtretyakov** [GoogleCloudPlatform/deploymentmanager-samples#92]
When using the following template to create database user referenced name property in output contains database name instead of [expected user name](https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/users):

`database.jinja`:

```yaml
{% set DATABASE_NAME = 'database' %}
{% set DATABASE_USER = 'username' %}

- name: create-user
  type: gcp-types/sqladmin-v1beta4:users
  properties:
    name: {{ DATABASE_USER }}
    instance: {{ DATABASE_NAME }}
    host: "cloudsqlproxy~%"

outputs:
- name: user
  value: $(ref.create-user.name)
```

It will return `database` instead of `username`.
