### ISSUE TITLE
Set roles for service account in jinja template

### ISSUE THREAD

**Issue by dtretyakov** [GoogleCloudPlatform/deploymentmanager-samples#94]
Currently I'm trying to use the following template to create service account and set roles for them:

`service-account.jinja`:
```yaml
{#
{% set BASE_NAME = env['deployment'] + '-' + env['name'] %}

resources:
- name: {{ BASE_NAME }}
  type: iam.v1.serviceAccount
  properties:
    accountId: {{ BASE_NAME }}
    displayName: {{ BASE_NAME }} service account

- name: set-account-roles
  action: gcp-types/iam-v1:iam.projects.serviceAccounts.setIamPolicy
  metadata:
    runtimePolicy:
    - CREATE
    dependsOn:
    -  {{ BASE_NAME }}
  properties:
    resource: $(ref.{{ BASE_NAME }}.name)
    policy:
      bindings:
      - role: 'roles/viewer'
        members:
        - serviceAccount:$(ref.{{ BASE_NAME }}.email)

outputs:
  - name: email
    value: $(ref.{{ BASE_NAME }}.email)
```

I'm running gcloud to deploy it under user with `owner` role, but it fails with a following error:
```json
{
  "ResourceType": "gcp-types/iam-v1:iam.projects.serviceAccounts.setIamPolicy",
  "ResourceErrorCode": "403",
  "ResourceErrorMessage": {
    "code": 403,
    "message": "Permission iam.serviceAccounts.setIamPolicy is required to perform this operation on service account projects/project-555/serviceAccounts/test7-service-account@project-555.iam.gserviceaccount.com.",
    "status": "PERMISSION_DENIED",
    "statusMessage": "Forbidden",
    "requestPath": "https://iam.googleapis.com/v1/projects/project-555/serviceAccounts/test7-service-account@project-555.iam.gserviceaccount.com:setIamPolicy",
    "httpMethod": "POST"
  }
}
```
What am I doing wrong?
